### PR TITLE
Upmerge 171120

### PR DESCRIPTION
**Pull request by de-nordic**
Update sdk/mcumgr fork with latest canges to zephyrproject-rtos/mcumgr fork.

### CODE REVIEW

**Review by ioannisg — APPROVED** [review]

**Comment by ioannisg** [comment]
Converted it to DRAFT, until it is approved.

**Comment by mbolivar-nordic** [comment]
I'm seeing a trailing whitespace difference between this PR and the upstream commit it says it's snapshotting:

```
$ git diff 8d087..manifest-rev
diff --git a/protocol.md b/protocol.md
index 9e79171..6684a72 100644
--- a/protocol.md
+++ b/protocol.md
@@ -86,7 +86,7 @@ type NmpHdr struct {
 SMP header (Little Endian)
 
- 0                   1                   2                   3  
+ 0                   1                   2                   3
  0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1
 +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
 |  OP |   Res.  |      Flags    |             Length            |
```

No other differences, though.

If we're trying to match the apache upstream exactly in NCS, though, I guess I'm wondering why we don't just point at the upstream commits directly? It doesn't seem like we have any out of tree code in here.

**Comment by de-nordic** [comment]
> 
> If we're trying to match the apache upstream exactly in NCS, though, I guess I'm wondering why we don't just point at the upstream commits directly? It doesn't seem like we have any out of tree code in here.

We are trying to match the  zephyrproject-rots/mcumgr "fork". The change has probably been accidental and has no impact on exection; the NCS for is completely following that "fork" so I do not find this as an issue. 

We may correct that style difference later, on zephyrprokect-rtos/mcumgr "fork", I do not see it as a blocker.

**Comment by mbolivar-nordic** [comment]
> I do not see it as a blocker.

Right, I never said that and I don't think it's a blocker either.

> We are trying to match the zephyrproject-rots/mcumgr "fork". 

OK, I see that f28a637 is the exact SHA which zephyr has in its master, so that makes sense. Thanks.

**Review by mbolivar-nordic — APPROVED** [review]

**Comment by de-nordic** [comment]
> 
> OK, I see that [f28a637](https://github.com/nrfconnect/sdk-mcumgr/commit/f28a637db12c4b12fb2b18bddc6b2a0deaa95251) is the exact SHA which zephyr has in its master, so that makes sense. Thanks.

Yes, basically we try to add changes to apache/mcumgr first, and then squash-chery-pick them to zephyrproject-rtos/mcumgr as snapshot updates; unfortunately there is no documentation for that process, so sometimes it happens in reverse order.

**Review by utzig — APPROVED** [review]

**Pull request merged**
